import type { Metadata } from "next";
import { inter } from "@/lib/fonts";
import { Toaster } from "@/components/ui/sonner";
import NextTopLoader from "nextjs-toploader";
import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.className} antialiased`}>
				<NextTopLoader color="#333" />
				{children}
				<Toaster position="top-right" duration={3000} closeButton richColors />
			</body>
		</html>
	);
}
